#此文件为默认配置请勿修改此文件

# cookies教程  
cookiesDoc: docs.qq.com/doc/DV2tDY2ltSFdtbU9z
# 米币签到成功是否推送
isPushSign: false
# 米游社米币签到定时任务，Cron表达式，默认00:02开始执行签到
mysBbsTime: 0 2 0 * * ? 
# 米币是否自动签到
ismysSign: true

# 签到成功是否推送
isAllSign: false
# 米游社签到定时任务，Cron表达式，默认00:02开始执行签到
allSignTime: 0 2 0 * * ? 
# 是否自动签到
isSign: true
# 默认签到游戏模板 仅支持 原神|崩坏3|崩坏2|未定事件簿
signlist:
 - 原神
 - 崩坏3
 - 崩坏2
 - 未定事件簿

# 云原神是否自动签到
isYunSign: true
# 米游社签到定时任务，Cron表达式，默认04:02开始执行签到
YunSignTime: 0 2 4 * * ? 
# 云原神签到成功是否推送
isYunSignMsg: false
# 云原神帮助
yunDoc: docs.qq.com/doc/DTnJIREZwTmxEVHBl



